export const equipmentOptions = [
  "Barbell",
  "Dumbbells",
  "Cable Machine",
  "Machine",
  "Bodyweight",
  "Kettlebell",
  "Resistance Bands",
  "Medicine Ball",
  "Pull-up Bar",
  "Bench",
  "Other",
];

export const muscleCategoryDetails: Array<{ category: string; muscles: string[] }> = [
  { category: "Chest", muscles: ["Upper chest", "Chest"] },
  { category: "Back", muscles: ["Back", "Traps", "Upper back", "Mid back", "Lats", "Erectors"] },
  { category: "Shoulders", muscles: ["Front delts", "Side delts", "Rear delts"] },
  { category: "Arms", muscles: ["Biceps", "Triceps", "Forearms"] },
  { category: "Core", muscles: ["Abs"] },
  { category: "Cardio", muscles: ["Cardio"] },
  { category: "Legs", muscles: ["Quads", "Hamstrings", "Calves", "Glutes"] },
  { category: "Neck", muscles: ["Neck"] },
];

export const muscleToCategory: Record<string, string> = {
  chest: "Chest",
  pectorals: "Chest",
  pecs: "Chest",
  "upper chest": "Chest",
  "lower chest": "Chest",
  back: "Back",
  lats: "Back",
  "latissimus dorsi": "Back",
  rhomboids: "Back",
  traps: "Back",
  trapezius: "Back",
  "lower back": "Back",
  "erector spinae": "Back",
  erectors: "Back",
  "rear delts": "Back",
  "upper back": "Back",
  "mid back": "Back",
  shoulders: "Shoulders",
  delts: "Shoulders",
  deltoids: "Shoulders",
  "front delts": "Shoulders",
  "side delts": "Shoulders",
  "lateral delts": "Shoulders",
  "anterior deltoid": "Shoulders",
  "posterior deltoid": "Shoulders",
  "rotator cuff": "Shoulders",
  arms: "Arms",
  biceps: "Arms",
  triceps: "Arms",
  forearms: "Arms",
  brachialis: "Arms",
  bicep: "Arms",
  tricep: "Arms",
  forearm: "Arms",
  wrists: "Arms",
  legs: "Legs",
  quads: "Legs",
  quadriceps: "Legs",
  hamstrings: "Legs",
  glutes: "Legs",
  gluteus: "Legs",
  calves: "Legs",
  calf: "Legs",
  "hip flexors": "Legs",
  adductors: "Legs",
  abductors: "Legs",
  thighs: "Legs",
  "lower body": "Legs",
  core: "Core",
  abs: "Core",
  abdominals: "Core",
  obliques: "Core",
  "lower abs": "Core",
  "upper abs": "Core",
  "transverse abdominis": "Core",
  hip: "Core",
  pelvis: "Core",
  "full body": "Full Body",
  compound: "Full Body",
  "total body": "Full Body",
  "whole body": "Full Body",
  cardio: "Cardio",
  cardiovascular: "Cardio",
  heart: "Cardio",
  conditioning: "Cardio",
  endurance: "Cardio",
  neck: "Neck",
  cervical: "Neck",
};

export const getCategoryFromMuscle = (muscle: string): string => {
  if (!muscle) return "Other";
  const normalized = muscle.toLowerCase().trim();
  if (muscleToCategory[normalized]) return muscleToCategory[normalized];
  for (const [key, category] of Object.entries(muscleToCategory)) {
    if (normalized.includes(key) || key.includes(normalized)) return category;
  }
  return "Other";
};
